material_index:
    path:     /
    defaults: { _controller: "MaterialBundle:Material:index" }
    methods:  GET

material_show:
    path:     /{id}/show
    defaults: { _controller: "MaterialBundle:Material:show" }
    methods:  GET

material_new:
    path:     /new
    defaults: { _controller: "MaterialBundle:Material:new" }
    methods:  [GET, POST]

material_edit:
    path:     /{id}/edit
    defaults: { _controller: "MaterialBundle:Material:edit" }
    methods:  [GET, POST]

material_delete:
    path:     /{id}/delete
    defaults: { _controller: "MaterialBundle:Material:delete" }
    methods:  DELETE
